language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
#script:
#  - pytest
deploy:
  provider: pypi
  user: jeremaihloo
  password:
    secure: jgnXk+urz/IPTlbQl5GdR8eGpEnJ3cr7mgGx0k6ktzm/91Dh/kaglZwX3yktZdwV2GokM84ipXIwgEOMwUleqdEwFG98TdKIl/WR+U+B4I2UgRzjgOx5kewg7HM1gvT9MkcjyAT0359y37/oLXbZOeuFKDi/FxJAs7lpneBaYeuVyUQS28Gzb5Q1rGFChR5fZj8LACMCCNvSfDfGb53MRVPR/4gq2mKLbFKoLkVz8zTLK5uAt0/poDPod8XMFWISKmCgr4C9kpfHkyjXk4ygIKrh0wdx2U1ULrQTx9+U+N56O8R1jtxEEiKBh1fH8NjJ/v87aA4PAX51RqamiEwtVdJNbEMCKSf12ThH2v9/gq2lndS+8rILJC+Y5Afbqfp2V3ZfqvvuSlKsmyO6I1tUyMpgxodr90zDczksRyZ8y0G2YiRX1A5XlTB4oTvFfLAK35FgDfqp4c2yxMuX/MyMyCBqs8Q424UZYcPmgmwOxBkYNBApaSGndcKPyZErTo0ZbHUzA8x0Tz1oQVQtJ8pLBwXpi2ll0FL3diRdyXXSuo2x9T0/cjfpIQjwNdiD6y0YHtbt+/BVSSRw+ZAx57A0SHTUBwrRGxoMLLqgPwLrEZPJOlMqL0O7X5DHTHiLeW8Bd/NQ5wYsCo5BpCcY/z2cJnZ01lvEzv2sy0zZU2f60k8=
