language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: jeremaihloo
  password:
    secure: KSIgAQlW6OIPjHicCVLzGYkYVS5l0b3mj5wpFx/PEnVhO+yeOTWoubfaJvJSxBtnTdtj5IhL4ymYonqUKi9v/3TpX49FcEZSDjuDMZkTOcgmqeCaD18tZn3Cj6FYCx9y8SMmssCh38T/2LI8AWBXesBjcFrF2CRVEHVphRWOcwUbhqlPpBykDPL2V5PHijbhP/BUxo3aEf956ukitjiXDC1dS+gPss5FVDAXrbkeNI0wMoNDc9Bj/oVSCECONhpTBXg0lTLdegNN8gcXmmp12Q9YPpCe1FAMpwbvGuwqktNwmkTIl/+dU9w9mMWSDLTLa7yTHN7c77qZBDko1izKQWPcOKqLosDBBE94TTn0hJT45oIz8OCZ6uGAbbhvxgvZg2YM5TZS6xkvvrcfYeleqJQNQQpGrfmhd4LlMjQciuA1ExjYrL1kUQmW1Yu8Wzs9oaIO9DzJHT5tCer0FfoFb1mqnmC33GVjkf9SCN0k8KeYfHMTJqASG+THiyIKK9qnbclKdoeh2g5/lMoolv+ajS/IQXSbc1c5lznCTwEMUcLQ1ElXK25wNSYpOh+odf32izIMtmWgroAuRlSFDJeJFTFo9m7b94lmTz0slVOWvKkVJ3rGpBP+QZsF4XQkzF5U4jGyDSDc7mbNl56W57sqMybC7n35meASGqvc+/E8qyg=
