language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: jeremaihloo
  password:
    secure: Ezw+QqYlmosxUyoDEyWdMDCFVMdwZPlvNLHfJSgSBaRxPWpyJf28XUdpkY25qegwXbi4s+vZodo40pXSSRr6PgEXAcB/7ftoAEf7Jv1mTb0/Viw/ziEwzYtXk1l3iEl69Fm4ZTER7mZoDapOVrGppVS/W+yQaz1Sd93gZmBxDZ1sDOJUqm5Z/Fgio8cjdhXbEZZjiSj6ACm2nmthGEO0XOtHrhet+mJCnHs6cnfrmGd1skA/zGu2lUENIBpCi0FK2XkV7akjepUE/FzG67JiNfr24aRsaBzkMyhDT+W8Xo31Y3YIbVHYEwV5E56f5mfD+U3m1DHsJg+Jhl0Z81FkHqItRvJvUn2DHI0C93gil/p7bjJq8VTYAhQxg8pv+NCOUsYFG1dzBqxiz0K7Myo2AiHYrFCWcqr58Dz76JloTG7fy5a2f1hqvpZB2bRrS3hv6iBJxBKsXrSTTFlEair/lZ87bPRbrJm0dVcKKmTdzZ3S3+MWdc00/SR6cNZEJ5Zuo2TB/+GuBxndf7ZaZ3GzMYbiXMSZQ9F7HyqGEUn2G2R/l3SY3t5N+W14oB7bQIXApT0dW5GclrPXMYmWmDUtJNpizwYzq5zk+W1UxS/JkDXl6yVfe9Ao3nJ7UGHbAeg3y2aKJ5k8kjnCgtAsIJm0uJV5mR2E5dDhIe5/FyLgiSY=
