language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: jeremaihloo
  password:
    secure: E23RnkQTZfd65Q8dZi4bYWz5+4IntSoB+O6LpGXqiphh+J0oO2WQ5ZYIq3P+Y2XV9HQR1cSgRcgaQyYBhv4gafivjAgIHCS4yZva5a38J1pfS9joZQ8TSAOCIh3U1YkyMExVAuLg6KEiFvPPFV4O+ZtxNcZZBBGPxb2KECQBYr4Z0Gxrm/cxv9d8bKv4f8ahVWWm1IEvft+Z+mIa6D8KztAq2htB664iAOTrvgGtveUIXnJImuErzrUkztu/HFGOj9IYNveTtGLSQuu2hbL7RDnBM+6Y4SQk3qo/DBUXwAqyFCAnr4itFjBiYzdTX6E647E9mkCLezFf5jSBeiqgx+TjQ+IfwvG1FFs1wLK9E7mmNQCoSwC8GIDcGDYAMWscpp5y/itzU1DT/VHE7M9vZ4ojUSfNS8oyzgOnpCDIbES7IiOk7S5eZHVniDmCfC7qnO7ltnn1KQw3Sg1Aeq9DcgRwnSva0YIiscfonzV2As37X3Z7xzUALvb8b2oytX+TuInz+AfFBssFL7TkY5sRpLeFYQPX8XP6BDaGN+kqfvsWfV3gq1srGxU0qIHnR3CcsJNaCCbFvq8/OyTBMKQRcdwPWux5XLeMyWY7pdKwMXE6oje/rFIIFaWKZgBe9oNQ0gUSVKf61lH1w9ZKnp6km1NdnMFWvd10QV1aDRtSmJQ=
